global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: $AWS_ACCESS_KEY_ID
        secret_key: $AWS_SECRET_ACCESS_KEY
        port: 9100

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost: 9093
rule_files:
  - 'rules.yml'
