commands:
    destroy_environment:
        steps:
            - run:
                name: Destroy environment
                command: |
                  aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7}
jobs:
# Exercise: Smoke Testing
    create_infrastructure:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            - run:
                name: Create Cloudformation Stack
                command: |
                  aws cloudformation deploy \
                    --template-file template.yml \
                    --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7} \
                    --region us-east-1
            - run:
                name: Simulate error
                command: |
                  return 1 # cause job to fail
            - destroy_environment
            - when: on_fail
# Sequential workflow
workflows:
  my_workflow:
      jobs:
        - create_infrastructure
        - smoke_test
