version: 2.1
jobs:
  create_infrastructure:
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys: ["${SSH_KEY_VALUE}"]
        - run:
            name: Install Ansible
            command: |
              apk add --update ansible
        - run:
            name: Configure EC2
            command: |
              ansible-playbook -i inventory template.yml
# Sequential workflow
workflows:
  my_workflow:
      jobs:
        - create_infrastructure
