---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install nodejs and npm"
  become: true
  apt:
    name: [nodejs,npm]
    state: latest
    update_cache: yes

- name: "Install PM2 packages"
  npm:
    name: pm2
    global: yes
    state: present

- name: "create /web directory"
  file:
    path: /web
    state: directory
    mode: 0755

- name: "install index.js file"
  copy:
    src: files/index.js
    dest: /web/index.js
    mode: 0775

- name: "start the application"
  command: pm2 start /web/index.js -f
